name: Build Dist

on:
  push:
    branches:
      - main

jobs:
  build-dist:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Building dist/
        run: pnpm build
      - name: Committing minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Github Action: Minified library"
