name: Minify Library

on:
  push:
    branches:
      - main

jobs:
  minify-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
          output: dist
          js_engine: uglify-js
      - name: Committing minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Github Action: Minified library"
